# This is a basic workflow to help you get started with Actions

name: Build docker image of adservice upon any change.

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths: 
      - 'src/adservice/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-docker-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/adservice

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#       Builds the docker image
      - name: build 
        run: sudo docker build ./ -t adservice
#        Testing purposes
#       - name: test
#         run: sudo docker images
        
      - name: login to harbor
        run: echo "${{ secrets.HARBOR_PWD }}" | docker login harbordemo351.tk -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: tag the image
        run: docker tag adservice harbordemo351.tk/demo/adservice
      
      - name: push the image
        run: docker push harbordemo351.tk/demo/adservice
