name: Run kube-bench for the EKS deployment.
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths: 
      - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kube-bench:
    # The type of runner that the job will run on
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./kube-bench
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: download kube-bench image and push
        run: |
              git clone https://github.com/aquasecurity/kube-bench.git
              cd kube-bench
              echo "${{ secrets.HARBOR_PWD }}" | sudo docker login harbordemo351.tk -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin
              sudo docker build -t k8s/kube-bench .
              sudo docker tag k8s/kube-bench:latest harbordemo351.tk/demo/kube-bench
              sudo docker push harbordemo351.tk/demo/kube-bench
      - name: dir
        run: ls
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: deploy as a job
        run: kubectl apply -f kube-bench/job-eks.yaml
          
      - name: find the pod and publish its logs
        run: kubectl logs | kubectl get pods --selector=job-name=pi --output=jsonpath='{.items[*].metadata.name}'
